2025-06-01 20:02:05,731 INFO    MainThread:9797 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-06-01 20:02:05,731 INFO    MainThread:9797 [wandb_setup.py:_flush():68] Configure stats pid to 9797
2025-06-01 20:02:05,731 INFO    MainThread:9797 [wandb_setup.py:_flush():68] Loading settings from /home/hugo/.config/wandb/settings
2025-06-01 20:02:05,731 INFO    MainThread:9797 [wandb_setup.py:_flush():68] Loading settings from /home/hugo/TFG/Notebooks/wandb/settings
2025-06-01 20:02:05,731 INFO    MainThread:9797 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/hugo/TFG/Notebooks/wandb/run-20250601_200205-odd46h6b/logs/debug.log
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/hugo/TFG/Notebooks/wandb/run-20250601_200205-odd46h6b/logs/debug-internal.log
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7c1940931e80>
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:init():852] calling init triggers
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'batch_size': 1000, 'learning_rate': 0.01, 'hidden_size': 98, 'epochs': 100, 'fold': 1, '_wandb': {}}
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:init():893] starting backend
2025-06-01 20:02:05,732 INFO    MainThread:9797 [wandb_init.py:init():897] sending inform_init request
2025-06-01 20:02:05,735 INFO    MainThread:9797 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-01 20:02:05,735 INFO    MainThread:9797 [wandb_init.py:init():907] backend started and connected
2025-06-01 20:02:05,737 INFO    MainThread:9797 [wandb_run.py:_label_probe_notebook():1369] probe notebook
2025-06-01 20:02:05,738 INFO    MainThread:9797 [wandb_init.py:init():1002] updated telemetry
2025-06-01 20:02:05,742 INFO    MainThread:9797 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-06-01 20:02:06,216 INFO    MainThread:9797 [wandb_init.py:init():1101] starting run threads in backend
2025-06-01 20:02:06,346 INFO    MainThread:9797 [wandb_run.py:_console_start():2566] atexit reg
2025-06-01 20:02:06,346 INFO    MainThread:9797 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-06-01 20:02:06,347 INFO    MainThread:9797 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-06-01 20:02:06,347 INFO    MainThread:9797 [wandb_run.py:_redirect():2506] Redirects installed.
2025-06-01 20:02:06,350 INFO    MainThread:9797 [wandb_init.py:init():1147] run started, returning control to user process
2025-06-01 20:02:43,446 INFO    MainThread:9797 [wandb_run.py:_config_callback():1429] config_cb ('_wandb', 'visualize', 'confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-06-01 20:02:44,267 INFO    MainThread:9797 [wandb_run.py:_finish():2314] finishing run TFG_Hugo/PRUEBA_FINALES_FOLDS/odd46h6b
2025-06-01 20:02:44,268 INFO    MainThread:9797 [jupyter.py:save_history():477] not saving jupyter history
2025-06-01 20:02:44,268 INFO    MainThread:9797 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-06-01 20:02:44,268 INFO    MainThread:9797 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-06-01 20:02:44,268 INFO    MainThread:9797 [wandb_run.py:_atexit_cleanup():2531] got exitcode: 0
2025-06-01 20:02:44,268 INFO    MainThread:9797 [wandb_run.py:_restore():2513] restore
2025-06-01 20:02:44,268 INFO    MainThread:9797 [wandb_run.py:_restore():2519] restore done
2025-06-01 20:03:10,785 WARNING MsgRouterThr:9797 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-01 20:03:10,787 INFO    MsgRouterThr:9797 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 3 handles.
2025-06-01 20:03:13,515 ERROR   MainThread:9797 [wandb_init.py:init():1660] [no run ID] error in wandb.init()
Traceback (most recent call last):
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1650, in init
    return wi.init(run_settings, run_config, run_printer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1009, in init
    backend.interface.publish_header()
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 97, in publish_header
    self._publish_header(header)
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 275, in _publish_header
    self._publish(rec)
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/hugo/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
